// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using RbRules.Infrastructure;

#nullable disable

namespace RbRules.Infrastructure.Migrations
{
    [DbContext(typeof(RbRulesDbContext))]
    [Migration("20260714135854_SourceFeeds")]
    partial class SourceFeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RbRules.Domain.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean")
                        .HasColumnName("blocked");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyAgenticQuota")
                        .HasColumnType("integer")
                        .HasColumnName("daily_agentic_quota");

                    b.Property<int>("DailyPhotoQuota")
                        .HasColumnType("integer")
                        .HasColumnName("daily_photo_quota");

                    b.Property<int>("DailyQuota")
                        .HasColumnType("integer")
                        .HasColumnName("daily_quota");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<byte[]>("PasskeyHandle")
                        .HasColumnType("bytea")
                        .HasColumnName("passkey_handle");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_email");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.AskMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Agentic")
                        .HasColumnType("boolean")
                        .HasColumnName("agentic");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("EscalatedBy")
                        .HasColumnType("text")
                        .HasColumnName("escalated_by");

                    b.Property<bool>("HadImage")
                        .HasColumnType("boolean")
                        .HasColumnName("had_image");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<bool>("Ok")
                        .HasColumnType("boolean")
                        .HasColumnName("ok");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<string>("QuestionType")
                        .HasColumnType("text")
                        .HasColumnName("question_type");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ask_metric");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ask_metric_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_ask_metric_user_id_created_at");

                    b.ToTable("ask_metric", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.AskTrace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Agentic")
                        .HasColumnType("boolean")
                        .HasColumnName("agentic");

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<string>("BrainSteps")
                        .HasColumnType("text")
                        .HasColumnName("brain_steps");

                    b.Property<string>("CommunityClaims")
                        .HasColumnType("text")
                        .HasColumnName("community_claims");

                    b.Property<string>("ContextCards")
                        .HasColumnType("text")
                        .HasColumnName("context_cards");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("EscalatedBy")
                        .HasColumnType("text")
                        .HasColumnName("escalated_by");

                    b.Property<bool>("HadImage")
                        .HasColumnType("boolean")
                        .HasColumnName("had_image");

                    b.Property<string>("History")
                        .HasColumnType("text")
                        .HasColumnName("history");

                    b.Property<string>("IpHash")
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<string>("MechanicMatches")
                        .HasColumnType("text")
                        .HasColumnName("mechanic_matches");

                    b.Property<bool>("MentionsCard")
                        .HasColumnType("boolean")
                        .HasColumnName("mentions_card");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<bool>("Ok")
                        .HasColumnType("boolean")
                        .HasColumnName("ok");

                    b.Property<string>("PhaseTimings")
                        .HasColumnType("text")
                        .HasColumnName("phase_timings");

                    b.Property<string>("PrimerDocs")
                        .HasColumnType("text")
                        .HasColumnName("primer_docs");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("QuestionType")
                        .HasColumnType("text")
                        .HasColumnName("question_type");

                    b.Property<string>("RewrittenQuery")
                        .HasColumnType("text")
                        .HasColumnName("rewritten_query");

                    b.Property<string>("Sections")
                        .HasColumnType("text")
                        .HasColumnName("sections");

                    b.Property<string>("SourceBias")
                        .HasColumnType("text")
                        .HasColumnName("source_bias");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("VerifiedRulings")
                        .HasColumnType("integer")
                        .HasColumnName("verified_rulings");

                    b.HasKey("Id")
                        .HasName("pk_ask_trace");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ask_trace_created_at");

                    b.HasIndex("IpHash", "CreatedAt")
                        .HasDatabaseName("ix_ask_trace_ip_hash_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_ask_trace_user_id_created_at");

                    b.ToTable("ask_trace", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.BanEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CardRiftboundId")
                        .HasColumnType("text")
                        .HasColumnName("card_riftbound_id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_ban_entry");

                    b.HasIndex("CardRiftboundId")
                        .HasDatabaseName("ix_ban_entry_card_riftbound_id");

                    b.ToTable("ban_entry", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.BenchmarkQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int?>("CorrectIndex")
                        .HasColumnType("integer")
                        .HasColumnName("correct_index");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_key");

                    b.PrimitiveCollection<string[]>("Options")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("options");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("Id")
                        .HasName("pk_benchmark_question");

                    b.HasIndex("ExternalKey")
                        .IsUnique()
                        .HasDatabaseName("ix_benchmark_question_external_key");

                    b.ToTable("benchmark_question", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.BenchmarkResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int?>("ChosenIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chosen_index");

                    b.Property<bool?>("Correct")
                        .HasColumnType("boolean")
                        .HasColumnName("correct");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.HasKey("Id")
                        .HasName("pk_benchmark_result");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_benchmark_result_question_id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_benchmark_result_run_id");

                    b.ToTable("benchmark_result", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.BenchmarkRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<int>("KeyedCount")
                        .HasColumnType("integer")
                        .HasColumnName("keyed_count");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<double?>("ScorePercent")
                        .HasColumnType("double precision")
                        .HasColumnName("score_percent");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_benchmark_run");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_benchmark_run_started_at");

                    b.ToTable("benchmark_run", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Card", b =>
                {
                    b.Property<string>("RiftboundId")
                        .HasColumnType("text")
                        .HasColumnName("riftbound_id");

                    b.Property<int?>("CollectorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("collector_number");

                    b.PrimitiveCollection<string[]>("Domains")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("domains");

                    b.PrimitiveCollection<string[]>("Effects")
                        .HasColumnType("text[]")
                        .HasColumnName("effects");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<int?>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.PrimitiveCollection<string[]>("Mechanics")
                        .HasColumnType("text[]")
                        .HasColumnName("mechanics");

                    b.Property<int?>("Might")
                        .HasColumnType("integer")
                        .HasColumnName("might");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.Property<string>("Rarity")
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<string>("SetId")
                        .HasColumnType("text")
                        .HasColumnName("set_id");

                    b.Property<string>("SetLabel")
                        .HasColumnType("text")
                        .HasColumnName("set_label");

                    b.Property<string>("Supertype")
                        .HasColumnType("text")
                        .HasColumnName("supertype");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TextPlain")
                        .HasColumnType("text")
                        .HasColumnName("text_plain");

                    b.PrimitiveCollection<string[]>("Triggers")
                        .HasColumnType("text[]")
                        .HasColumnName("triggers");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VariantOf")
                        .HasColumnType("text")
                        .HasColumnName("variant_of");

                    b.HasKey("RiftboundId")
                        .HasName("pk_card");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_card_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_card_name");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_card_set_id");

                    b.ToTable("card", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.CardInteraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CardAId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_a_id");

                    b.Property<string>("CardBId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_b_id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_card_interaction");

                    b.HasIndex("CardAId")
                        .HasDatabaseName("ix_card_interaction_card_a_id");

                    b.HasIndex("CardBId")
                        .HasDatabaseName("ix_card_interaction_card_b_id");

                    b.HasIndex("CardAId", "CardBId")
                        .IsUnique()
                        .HasDatabaseName("ix_card_interaction_card_a_id_card_b_id");

                    b.ToTable("card_interaction", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.CardSet", b =>
                {
                    b.Property<string>("SetId")
                        .HasColumnType("text")
                        .HasColumnName("set_id");

                    b.Property<int?>("CardCount")
                        .HasColumnType("integer")
                        .HasColumnName("card_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("PublishedOn")
                        .HasColumnType("date")
                        .HasColumnName("published_on");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("SetId")
                        .HasName("pk_card_set");

                    b.ToTable("card_set", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Change", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Diff")
                        .HasColumnType("text")
                        .HasColumnName("diff");

                    b.Property<string>("Meaning")
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_change");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("ix_change_detected_at");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_change_source_id");

                    b.ToTable("change", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Claim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<int>("Corroboration")
                        .HasColumnType("integer")
                        .HasColumnName("corroboration");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("OfficialStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("official_status");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text")
                        .HasColumnName("status_reason");

                    b.Property<string>("TopicRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic_ref");

                    b.Property<string>("TopicType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic_type");

                    b.Property<double>("TrustScore")
                        .HasColumnType("double precision")
                        .HasColumnName("trust_score");

                    b.HasKey("Id")
                        .HasName("pk_claim");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_claim_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_claim_status");

                    b.HasIndex("TopicType", "TopicRef")
                        .HasDatabaseName("ix_claim_topic_type_topic_ref");

                    b.ToTable("claim", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.ClaimSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint")
                        .HasColumnName("claim_id");

                    b.Property<string>("QuoteExcerpt")
                        .HasColumnType("text")
                        .HasColumnName("quote_excerpt");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_claim_source");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_claim_source_source_id");

                    b.HasIndex("ClaimId", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_claim_source_claim_id_source_id");

                    b.ToTable("claim_source", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Conflict", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("SourceAId")
                        .HasColumnType("text")
                        .HasColumnName("source_a_id");

                    b.Property<string>("SourceBId")
                        .HasColumnType("text")
                        .HasColumnName("source_b_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<string>("WinnerSourceId")
                        .HasColumnType("text")
                        .HasColumnName("winner_source_id");

                    b.HasKey("Id")
                        .HasName("pk_conflict");

                    b.HasIndex("SourceAId")
                        .HasDatabaseName("ix_conflict_source_a_id");

                    b.HasIndex("SourceBId")
                        .HasDatabaseName("ix_conflict_source_b_id");

                    b.HasIndex("WinnerSourceId")
                        .HasDatabaseName("ix_conflict_winner_source_id");

                    b.ToTable("conflict", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Correction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("Provenance")
                        .HasColumnType("text")
                        .HasColumnName("provenance");

                    b.Property<string>("Question")
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_correction");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_correction_status");

                    b.ToTable("correction", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Deck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<string[]>("Domains")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("domains");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<int>("Likes")
                        .HasColumnType("integer")
                        .HasColumnName("likes");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PaCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pa_created_at");

                    b.Property<string>("PaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pa_id");

                    b.Property<DateTimeOffset?>("PaUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pa_updated_at");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<int>("Views")
                        .HasColumnType("integer")
                        .HasColumnName("views");

                    b.HasKey("Id")
                        .HasName("pk_deck");

                    b.HasIndex("PaId")
                        .IsUnique()
                        .HasDatabaseName("ix_deck_pa_id");

                    b.ToTable("deck", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.DeckCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalRiftboundId")
                        .HasColumnType("text")
                        .HasColumnName("canonical_riftbound_id");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_code");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.HasKey("Id")
                        .HasName("pk_deck_card");

                    b.HasIndex("CanonicalRiftboundId")
                        .HasDatabaseName("ix_deck_card_canonical_riftbound_id");

                    b.HasIndex("DeckId")
                        .HasDatabaseName("ix_deck_card_deck_id");

                    b.ToTable("deck_card", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClaimsMinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claims_mined_at");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("SourceId", "RetrievedAt")
                        .HasDatabaseName("ix_document_source_id_retrieved_at");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Erratum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_name");

                    b.Property<string>("CardRiftboundId")
                        .HasColumnType("text")
                        .HasColumnName("card_riftbound_id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("NewText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_erratum");

                    b.HasIndex("CardRiftboundId")
                        .HasDatabaseName("ix_erratum_card_riftbound_id");

                    b.ToTable("erratum", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.KnowledgeDoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("RelationsMinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("relations_mined_at");

                    b.Property<string>("SectionRefs")
                        .HasColumnType("text")
                        .HasColumnName("section_refs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_doc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_knowledge_doc_status");

                    b.HasIndex("Kind", "Topic")
                        .IsUnique()
                        .HasDatabaseName("ix_knowledge_doc_kind_topic");

                    b.ToTable("knowledge_doc", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.LoginToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_login_token");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_login_token_email");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_login_token_token_hash");

                    b.ToTable("login_token", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.MechanicKeyword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("term");

                    b.HasKey("Id")
                        .HasName("pk_mechanic_keyword");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_mechanic_keyword_status");

                    b.HasIndex("Term")
                        .IsUnique()
                        .HasDatabaseName("ix_mechanic_keyword_term");

                    b.ToTable("mechanic_keyword", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.PasskeyChallenge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("options_json");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_passkey_challenge");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_passkey_challenge_token_hash");

                    b.ToTable("passkey_challenge", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.PasskeyCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Aaguid")
                        .HasColumnType("uuid")
                        .HasColumnName("aaguid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("credential_id");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sign_count");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_passkey_credential");

                    b.HasIndex("CredentialId")
                        .IsUnique()
                        .HasDatabaseName("ix_passkey_credential_credential_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_passkey_credential_user_id");

                    b.ToTable("passkey_credential", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.PushSubscription", b =>
                {
                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.HasKey("Endpoint")
                        .HasName("pk_push_subscription");

                    b.ToTable("push_subscription", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Relation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("FromRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_ref");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provenance");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_ref");

                    b.Property<double>("Trust")
                        .HasColumnType("double precision")
                        .HasColumnName("trust");

                    b.HasKey("Id")
                        .HasName("pk_relation");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_relation_status");

                    b.HasIndex("FromRef", "ToRef", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_relation_from_ref_to_ref_kind");

                    b.ToTable("relation", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.RelationKind", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_relation_kind");

                    b.HasIndex("Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_relation_kind_kind");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_relation_kind_status");

                    b.ToTable("relation_kind", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.RuleChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<int?>("Page")
                        .HasColumnType("integer")
                        .HasColumnName("page");

                    b.Property<string>("SectionCode")
                        .HasColumnType("text")
                        .HasColumnName("section_code");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_rule_chunk");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_rule_chunk_document_id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_rule_chunk_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_rule_chunk_source_id");

                    b.ToTable("rule_chunk", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.RunLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Ref")
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_run_log");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_run_log_created_at");

                    b.ToTable("run_log", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.SimilarityExplanation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CardAId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_a_id");

                    b.Property<string>("CardBId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_b_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_similarity_explanation");

                    b.HasIndex("CardAId", "CardBId")
                        .IsUnique()
                        .HasDatabaseName("ix_similarity_explanation_card_a_id_card_b_id");

                    b.ToTable("similarity_explanation", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cadence");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FeedId")
                        .HasColumnType("text")
                        .HasColumnName("feed_id");

                    b.Property<DateTimeOffset?>("LastChecked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked");

                    b.Property<string>("LastHash")
                        .HasColumnType("text")
                        .HasColumnName("last_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Parser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<short>("TrustTier")
                        .HasColumnType("smallint")
                        .HasColumnName("trust_tier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_source");

                    b.HasIndex("FeedId")
                        .HasDatabaseName("ix_source_feed_id");

                    b.ToTable("source", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.SourceFeed", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("AutoApprove")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_approve");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cadence");

                    b.Property<string>("CategoryFilter")
                        .HasColumnType("text")
                        .HasColumnName("category_filter");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastChecked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked");

                    b.Property<string>("LastHash")
                        .HasColumnType("text")
                        .HasColumnName("last_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_source_feed");

                    b.ToTable("source_feed", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.SourceProposal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("found_at");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_source_proposal");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_source_proposal_status");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_source_proposal_url");

                    b.ToTable("source_proposal", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_session");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_session_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_session_user_id");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.BenchmarkResult", b =>
                {
                    b.HasOne("RbRules.Domain.BenchmarkQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_benchmark_result_benchmark_question_question_id");

                    b.HasOne("RbRules.Domain.BenchmarkRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_benchmark_result_benchmark_run_run_id");

                    b.Navigation("Question");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("RbRules.Domain.Change", b =>
                {
                    b.HasOne("RbRules.Domain.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_change_source_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("RbRules.Domain.ClaimSource", b =>
                {
                    b.HasOne("RbRules.Domain.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claim_source_claim_claim_id");

                    b.HasOne("RbRules.Domain.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claim_source_source_source_id");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("RbRules.Domain.Conflict", b =>
                {
                    b.HasOne("RbRules.Domain.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_conflict_source_source_a_id");

                    b.HasOne("RbRules.Domain.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceBId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_conflict_source_source_b_id");

                    b.HasOne("RbRules.Domain.Source", null)
                        .WithMany()
                        .HasForeignKey("WinnerSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_conflict_source_winner_source_id");
                });

            modelBuilder.Entity("RbRules.Domain.DeckCard", b =>
                {
                    b.HasOne("RbRules.Domain.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deck_card_deck_deck_id");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("RbRules.Domain.Document", b =>
                {
                    b.HasOne("RbRules.Domain.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_source_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("RbRules.Domain.PasskeyCredential", b =>
                {
                    b.HasOne("RbRules.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_passkey_credential_app_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RbRules.Domain.RuleChunk", b =>
                {
                    b.HasOne("RbRules.Domain.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rule_chunk_document_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RbRules.Domain.Source", b =>
                {
                    b.HasOne("RbRules.Domain.SourceFeed", null)
                        .WithMany()
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_source_source_feeds_feed_id");
                });

            modelBuilder.Entity("RbRules.Domain.UserSession", b =>
                {
                    b.HasOne("RbRules.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_session_app_user_user_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
