// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using RbRules.Infrastructure;

#nullable disable

namespace RbRules.Infrastructure.Migrations
{
    [DbContext(typeof(RbRulesDbContext))]
    partial class RbRulesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RbRules.Domain.Card", b =>
                {
                    b.Property<string>("RiftboundId")
                        .HasColumnType("text")
                        .HasColumnName("riftbound_id");

                    b.Property<int?>("CollectorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("collector_number");

                    b.PrimitiveCollection<string[]>("Domains")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("domains");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<int?>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int?>("Might")
                        .HasColumnType("integer")
                        .HasColumnName("might");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.Property<string>("Rarity")
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<string>("SetId")
                        .HasColumnType("text")
                        .HasColumnName("set_id");

                    b.Property<string>("SetLabel")
                        .HasColumnType("text")
                        .HasColumnName("set_label");

                    b.Property<string>("Supertype")
                        .HasColumnType("text")
                        .HasColumnName("supertype");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TextPlain")
                        .HasColumnType("text")
                        .HasColumnName("text_plain");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RiftboundId")
                        .HasName("pk_card");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_card_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_card_name");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_card_set_id");

                    b.ToTable("card", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.CardSet", b =>
                {
                    b.Property<string>("SetId")
                        .HasColumnType("text")
                        .HasColumnName("set_id");

                    b.Property<int?>("CardCount")
                        .HasColumnType("integer")
                        .HasColumnName("card_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("PublishedOn")
                        .HasColumnType("date")
                        .HasColumnName("published_on");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("SetId")
                        .HasName("pk_card_set");

                    b.ToTable("card_set", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Change", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Diff")
                        .HasColumnType("text")
                        .HasColumnName("diff");

                    b.Property<string>("Meaning")
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_change");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("ix_change_detected_at");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_change_source_id");

                    b.ToTable("change", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Conflict", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("SourceAId")
                        .HasColumnType("text")
                        .HasColumnName("source_a_id");

                    b.Property<string>("SourceBId")
                        .HasColumnType("text")
                        .HasColumnName("source_b_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<string>("WinnerSourceId")
                        .HasColumnType("text")
                        .HasColumnName("winner_source_id");

                    b.HasKey("Id")
                        .HasName("pk_conflict");

                    b.HasIndex("SourceAId")
                        .HasDatabaseName("ix_conflict_source_a_id");

                    b.HasIndex("SourceBId")
                        .HasDatabaseName("ix_conflict_source_b_id");

                    b.HasIndex("WinnerSourceId")
                        .HasDatabaseName("ix_conflict_winner_source_id");

                    b.ToTable("conflict", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Correction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("Provenance")
                        .HasColumnType("text")
                        .HasColumnName("provenance");

                    b.Property<string>("Question")
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_correction");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_correction_status");

                    b.ToTable("correction", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("SourceId", "RetrievedAt")
                        .HasDatabaseName("ix_document_source_id_retrieved_at");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.PushSubscription", b =>
                {
                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.HasKey("Endpoint")
                        .HasName("pk_push_subscription");

                    b.ToTable("push_subscription", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.RuleChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<string>("SectionCode")
                        .HasColumnType("text")
                        .HasColumnName("section_code");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_rule_chunk");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_rule_chunk_document_id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_rule_chunk_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_rule_chunk_source_id");

                    b.ToTable("rule_chunk", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.RunLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Ref")
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_run_log");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_run_log_created_at");

                    b.ToTable("run_log", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cadence");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastChecked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked");

                    b.Property<string>("LastHash")
                        .HasColumnType("text")
                        .HasColumnName("last_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Parser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<short>("TrustTier")
                        .HasColumnType("smallint")
                        .HasColumnName("trust_tier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_source");

                    b.ToTable("source", (string)null);
                });

            modelBuilder.Entity("RbRules.Domain.Change", b =>
                {
                    b.HasOne("RbRules.Domain.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_change_source_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("RbRules.Domain.Conflict", b =>
                {
                    b.HasOne("RbRules.Domain.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_conflict_source_source_a_id");

                    b.HasOne("RbRules.Domain.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceBId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_conflict_source_source_b_id");

                    b.HasOne("RbRules.Domain.Source", null)
                        .WithMany()
                        .HasForeignKey("WinnerSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_conflict_source_winner_source_id");
                });

            modelBuilder.Entity("RbRules.Domain.Document", b =>
                {
                    b.HasOne("RbRules.Domain.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_source_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("RbRules.Domain.RuleChunk", b =>
                {
                    b.HasOne("RbRules.Domain.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rule_chunk_document_document_id");

                    b.Navigation("Document");
                });
#pragma warning restore 612, 618
        }
    }
}
